name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:    
       - name: Checkout
         uses: actions/checkout@v3
       - name: alire-project/setup-alire@v2
         uses: alire-project/setup-alire@v2
       - name: Build
         run: |
            alr --no-tty build
